apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ssdcxy/adm_backend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_SERVICE_HOST
              value: 'mysql'
            - name: MYSQL_SERVICE_PORT
              value: '3306'