apiVersion: v1
kind: ReplicationController # 副本控制器RC
metadata:
    name: mysql # RC的名称，全局唯一
spec:
    replicas: 1 # Pod副本期待数量
    selector:
        app: mysql  # 符合目标的Pod拥有此标签
    template:   # 根据此模版创建Pod的副本
        metadata:
            labels:
                app: mysql  # Pod副本拥有的标签，对应RC的Selector
        spec:
            containers: # Pod内容器的定义部分
                - name: mysql   # 容器的名称
                  image: mysql:5.7  # 容器对应的Docker image
                  args:
                    - "--ignore-db-dir=lost+found"
                    - "--character-set-server=utf8mb4"     #  指定字符编码
                #   resources:
                #     requests:
                #         memory: "256Mi"
                #         cpu: "125m"
                #     limits:
                #         memory: "512Mi"
                #         cpu: "500m"
                  ports:
                    - containerPort: 3306   # 容器应用监听的端口
                  env:  # 注入容器内的环境变量
                    - name: MYSQL_ROOT_PASSWORD
                      value: "123456"
                    - name: MYSQL_USER     #  新建用户的用户名
                      value: app_user
                    - name: MYSQL_PASSWORD        # 新建的用户
                      value: NvUyzlY@x9TQD!vc
                    - name: MYSQL_DATABASE    # 新建的数据库
                      value: adm
