server:
  port: 8000
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://rm-bp1673j5245w1f4y2wo.mysql.rds.aliyuncs.com:3306/adm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
  # 单机模式
    database: 1
    host: 116.62.55.220
    port: 6379
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl